export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";

export const SIGNUP_SUCCESS = "REGISTER_SUCCESS";
export const SIGNUP_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";
export const RESET_PASSWORD = "RESET_PASSWORD";
